### PR TITLE
v5.4.0

### PR DESCRIPTION
**Pull request by co-zz-deRitter**
Added The Pope

### CODE REVIEW

**Comment by pickten** [comment]
The new update will have a boost to do this, I believe (Papal Staff).

**Comment by co-zz-deRitter** [comment]
Good to know. I can certainly remove it from BeachBall when the update goes out.

**Comment by pickten** [comment]
Actually, just looked for it and couldn't find it, so it might have just been something we were considering. When the update is released, things will be clearer.

**Comment by co-zz-deRitter** [comment]
The name was Permanent Staff when I looked. And it looks like it requires 144 Papal Decrees anyway, so maybe The Pope in BeachBall is still a useful tool.

**Comment by pickten** [comment]
I see it, just missed it the first time. Good catch.

**Pull request merged**
